/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a MyMessageAdaptor MyMessage.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "MyMessageAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MyMessageAdaptor
 */

MyMessageAdaptor::MyMessageAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MyMessageAdaptor::~MyMessageAdaptor()
{
    // destructor
}

void MyMessageAdaptor::sendSignal(const QString &signal)
{
    // handle method call Demo.MyMessage.sendSignal
    QMetaObject::invokeMethod(parent(), "sendSignal", Q_ARG(QString, signal));
}

