/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp MyMessage.xml -a MyMessageAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "MyMessageAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MyMessageAdaptor
 */

MyMessageAdaptor::MyMessageAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MyMessageAdaptor::~MyMessageAdaptor()
{
    // destructor
}

void MyMessageAdaptor::sendMessage(Message message)
{
    // handle method call Demo.MyMessage.sendMessage
    QMetaObject::invokeMethod(parent(), "sendMessage", Q_ARG(Message, message));
}

void MyMessageAdaptor::sendMessage2(messageList message)
{
    // handle method call Demo.MyMessage.sendMessage2
    QMetaObject::invokeMethod(parent(), "sendMessage2", Q_ARG(messageList, message));
}

void MyMessageAdaptor::sendSignal(const QString &signal)
{
    // handle method call Demo.MyMessage.sendSignal
    QMetaObject::invokeMethod(parent(), "sendSignal", Q_ARG(QString, signal));
}

void MyMessageAdaptor::sendSignal2(const QList<int> &signal2)
{
    // handle method call Demo.MyMessage.sendSignal2
    QMetaObject::invokeMethod(parent(), "sendSignal2", Q_ARG(QList<int>, signal2));
}

