/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp MyMessage.xml -a MyMessageAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MYMESSAGEADAPTOR_H_1455488104
#define MYMESSAGEADAPTOR_H_1455488104

#include <QtCore/QObject>
#include <QtDBus/QtDBus>

#include "../Message/message.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface Demo.MyMessage
 */
class MyMessageAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "Demo.MyMessage")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"Demo.MyMessage\">\n"
"    <method name=\"sendMessage\">\n"
"      <arg type=\"a(iiis)\" name=\"message\"/>\n"
"      <annotation value=\"Message\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"sendMessage2\">\n"
"      <arg type=\"a(ii)\" name=\"message\"/>\n"
"      <annotation value=\"messageList\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"sendSignal\">\n"
"      <arg type=\"s\" name=\"signal\"/>\n"
"    </method>\n"
"    <method name=\"sendSignal2\">\n"
"      <arg type=\"ai\" name=\"signal2\"/>\n"
"      <annotation value=\"QList&lt;int&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    MyMessageAdaptor(QObject *parent);
    virtual ~MyMessageAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void sendMessage(Message message);
    void sendMessage2(messageList message);
    void sendSignal(const QString &signal);
    void sendSignal2(const QList<int> &signal2);
Q_SIGNALS: // SIGNALS
};

#endif
