/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a MyMessageAdaptor MyMessage.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MYMESSAGEADAPTOR_H
#define MYMESSAGEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface Demo.MyMessage
 */
class MyMessageAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "Demo.MyMessage")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"Demo.MyMessage\">\n"
"    <method name=\"sendSignal\">\n"
"      <arg type=\"s\" name=\"signal\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    MyMessageAdaptor(QObject *parent);
    virtual ~MyMessageAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void sendSignal(const QString &signal);
Q_SIGNALS: // SIGNALS
};

#endif
