/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p MyMessageInterface MyMessage.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MYMESSAGEINTERFACE_H
#define MYMESSAGEINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface Demo.MyMessage
 */
class DemoMyMessageInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "Demo.MyMessage"; }

public:
    DemoMyMessageInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~DemoMyMessageInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> sendSignal(const QString &signal)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(signal);
        return asyncCallWithArgumentList(QStringLiteral("sendSignal"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace Demo {
  typedef ::DemoMyMessageInterface MyMessage;
}
#endif
